# Generated by Django 6.0.5 on 2026-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Haircut', 'Haircut'), ('Beard Trim', 'Beard Trim'), ('Haircut + Beard', 'Haircut + Beard'), ('Hair Dyeing', 'Hair Dyeing'), ('Children Haircut', 'Children Haircut')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
    ]
