# Generated by Django 6.0.5 on 2026-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_barber_appointment_barber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
