# Generated by Django 6.0.5 on 2026-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
